### ISSUE TITLE
Duvida

### ISSUE THREAD

**Issue by ghost** [intelipost/job-mobile-developer#4]
Olá, eu gostaria de entender nesse novo merge feito nesse repositório, sobre o novo quesito do desafio que é:

> _Também ter uma tela que liste notícias com foto e que seja possível ver a noticia por completo, pode usar qualquer api externa ou criar um mock de API._  

Bom foge um pouco do contexto do projeto inicial, ou de onde vem essas noticias ou que noticias? ficou um pouco confuso, só gostaria de um esclarecimento sobre tal quesito.

**Comment by gustavointelipost** [comment]
Oi Carlos, você pode pegar as notícias de onde achar mais conveniente, de uma api que tenha pública ou algo parecido.

**Comment by ghost** [comment]
Entendi, muito obrigado pelo esclarecimento
